export const categories = [
  "Quantitative Aptitude for SSC",
  "General Intelligence & Reasoning for SSC",
  "English Comprehension for SSC",
  "General Awareness for SSC",
  "General Science for SSC",
  "Quantitative Aptitude for Banking",
  "Reasoning Ability for Banking",
  "English Language for Banking",
  "General Awareness for Banking",
  "Banking & Financial Awareness for Banking",
  "Computer Awareness for Banking",
  "Data Interpretation for Banking",
  "Mathematics for Railways",
  "General Intelligence & Reasoning for Railways",
  "General Awareness for Railways",
  "General Science for Railways",
  "Current Affairs for Railways",
  "Quantitative Aptitude for State PSC",
  "Reasoning Ability for State PSC",
  "General Knowledge for State PSC",
  "Current Affairs for State PSC",
  "State Specific GK for State PSC",
  "Indian Polity for State PSC",
  "Economy for State PSC",
  "Quantitative Aptitude for Defence",
  "Reasoning Ability for Defence",
  "General Knowledge for Defence",
  "General Science for Defence",
  "English Language for Defence",
  "Defence Awareness for Defence",
  "Indian Polity for UPSC",
  "History for UPSC",
  "Geography for UPSC",
  "Economy for UPSC",
  "Environment & Ecology for UPSC",
  "Science & Technology for UPSC",
  "Current Affairs for UPSC",
  "Ethics & Integrity for UPSC",
  "Essay Writing for UPSC",
  "Reasoning Ability for Police",
  "Quantitative Aptitude for Police",
  "General Knowledge for Police",
  "General Science for Police",
  "Current Affairs for Police",
  "Child Development & Pedagogy for Teaching",
  "Teaching Aptitude for Teaching",
  "English Language for Teaching",
  "Hindi Language for Teaching",
  "Mathematics for Teaching",
  "Environmental Studies for Teaching",
  "Engineering Mathematics for Engineering",
  "Civil Engineering for Engineering",
  "Mechanical Engineering for Engineering",
  "Electrical Engineering for Engineering",
  "Electronics Engineering for Engineering",
  "Computer Science for Engineering",
  "General Aptitude for Engineering",
  "Anatomy & Physiology for Paramedical",
  "Nursing Foundations for Paramedical",
  "Pharmacology for Paramedical",
  "Medical Surgical Nursing for Paramedical",
  "Community Health Nursing for Paramedical",
  "General Science for Paramedical",
  "Financial Accounting for Commerce",
  "Cost Accounting for Commerce",
  "Auditing for Commerce",
  "Business Studies for Commerce",
  "Economics for Commerce",
  "Taxation for Commerce",
  "Quantitative Aptitude for MBA",
  "Logical Reasoning for MBA",
  "Data Interpretation for MBA",
  "Verbal Ability for MBA",
  "Decision Making for MBA",
  "General Awareness for MBA",
  "Quantitative Aptitude for UG",
  "Logical Reasoning for UG",
  "General Knowledge for UG",
  "English Language for UG",
  "Subject Knowledge for UG"
];